# Generated by Django 6.0.2 on 2026-03-12 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0003_article_show_contact_form'),
        ('pages', '0004_page_show_contact_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_home', models.BooleanField(default=False, help_text='Show this slider on the home page')),
                ('show_on_all_pages', models.BooleanField(default=False, help_text='Show this slider on all CMS pages (overridden by specific page assignment)')),
                ('show_on_all_news', models.BooleanField(default=False, help_text='Show this slider on the news list and all article pages (overridden by specific article assignment)')),
                ('articles', models.ManyToManyField(blank=True, help_text='Show this slider on specific news articles', related_name='sliders', to='news.article')),
                ('pages', models.ManyToManyField(blank=True, help_text='Show this slider on specific pages', related_name='sliders', to='pages.page')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/')),
                ('alt', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200)),
                ('link', models.CharField(blank=True, help_text='Optional URL when clicking the image', max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='slider.slider')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
