# Generated by Django 6.0.2 on 2026-03-12 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_show_contact_form'),
        ('pages', '0004_page_show_contact_form'),
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimage',
            name='link',
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='article_link',
            field=models.ForeignKey(blank=True, help_text='Select a news article (used when Link type = Internal – News article)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='news.article'),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='external_url',
            field=models.CharField(blank=True, help_text='Full URL, e.g. https://example.com (used when Link type = External URL)', max_length=500),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='link_new_tab',
            field=models.BooleanField(default=False, help_text='Open link in a new browser tab (recommended for external links)'),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='link_type',
            field=models.CharField(choices=[('none', 'No link'), ('internal_page', 'Internal – Page'), ('internal_article', 'Internal – News article'), ('external', 'External URL')], default='none', help_text='Type of link attached to this image', max_length=20),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='page_link',
            field=models.ForeignKey(blank=True, help_text='Select an internal page (used when Link type = Internal – Page)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.page'),
        ),
    ]
